services:
  - type: web
    name: classroom-video-analyzer
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_KEYS_JSON
        sync: false
      - key: PORT
        value: 8001
      - key: PYTHONUNBUFFERED
        value: "1"
